#
# Jekyll configuration
#
#server: true
destination: ./_site
auto:        false
#server_port: 4000
permalink:   pretty
#paginate:    20
lsi:         true
#lsi:         false
pygments:    true
#markdown:    maruku
markdown:    rdiscount

#
# Site configuration
#
url:          http://www.nata2.org
title:        "Harper Reed: Technology and death metal"
description:  Hacking, Baphomet and the real time internet
author:       Harper Reed # atom.xml: Name of website's author
email:        harper@nata2.org # atom.xml: Author email
analytics_id: UA-70650-9 # Google Analytics ID: UA-xxx-xxx
media_version: 8
media_server: "" #http://media.nata2.org
